---
- name: "GRUB configuration"
  hosts: target
  tasks:
    - name: "Configure grub"
      copy:
        src: "../files/{{ item }}"
        dest: "/etc/default/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - grub

    - name: "Update grub.conf"
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg
